#!/bin/bash
# ==========================================
# HeaNg[Black-Cyber] Security Setup Guide
# ==========================================
# This script helps you understand and configure the security system

echo "🛡️ HeaNg[Black-Cyber] Security System Documentation"
echo "=================================================="
echo ""

echo "📋 SECURITY FEATURES IMPLEMENTED:"
echo "================================="
echo ""

echo "1. CLIENT-SIDE PROTECTION (security.js)"
echo "   ✓ F12 Key Blocking"
echo "   ✓ Inspect Element Prevention"
echo "   ✓ Developer Tools Detection"
echo "   ✓ Context Menu (Right-click) Blocking"
echo "   ✓ Source Map Access Prevention"
echo "   ✓ Console Access Protection"
echo "   ✓ Debugger Detection"
echo "   ✓ Session Monitoring"
echo "   ✓ Copy/Paste Control"
echo "   ✓ Drag & Drop Prevention"
echo ""

echo "2. SPAM & RATE LIMITING"
echo "   ✓ Per-minute rate limiting (20 requests/minute)"
echo "   ✓ Per-hour rate limiting (200 requests/hour)"
echo "   ✓ Per-day rate limiting (2000 requests/day)"
echo "   ✓ Sliding window algorithm"
echo "   ✓ Automatic IP blocking after limit exceeded"
echo "   ✓ Message rate limiting (100 messages/hour)"
echo ""

echo "3. SPAM DETECTION"
echo "   ✓ Repeated character detection (20+)"
echo "   ✓ Multiple URL detection"
echo "   ✓ Excessive special character detection"
echo "   ✓ Repeated word detection (10+)"
echo "   ✓ Spam keyword filtering"
echo "   ✓ Script injection detection"
echo "   ✓ SQL injection detection"
echo ""

echo "4. INPUT VALIDATION"
echo "   ✓ Message format validation"
echo "   ✓ Content length validation (5000 chars/message)"
echo "   ✓ Total payload validation (15000 chars)"
echo "   ✓ Message count validation (50 max)"
echo "   ✓ Role validation (user/assistant/system)"
echo "   ✓ HTML/Script sanitization"
echo ""

echo "5. XSS PROTECTION"
echo "   ✓ Content Security Policy (CSP)"
echo "   ✓ HTML escaping"
echo "   ✓ innerHTML protection"
echo "   ✓ Safe DOM manipulation"
echo "   ✓ Script tag filtering"
echo ""

echo "6. USER-AGENT VALIDATION"
echo "   ✓ Malicious bot blocking (sqlmap, nikto, nmap, etc.)"
echo "   ✓ Legitimate bot allowlist (Google, Bing, DuckDuckGo)"
echo "   ✓ Curl/wget blocking"
echo ""

echo "7. SECURITY HEADERS"
echo "   ✓ X-Content-Type-Options: nosniff"
echo "   ✓ X-Frame-Options: SAMEORIGIN"
echo "   ✓ X-XSS-Protection: 1; mode=block"
echo "   ✓ Strict-Transport-Security"
echo "   ✓ Content-Security-Policy"
echo "   ✓ Referrer-Policy: strict-origin-when-cross-origin"
echo "   ✓ Permissions-Policy (geolocation, microphone, camera)"
echo ""

echo "8. CSRF PROTECTION"
echo "   ✓ CSRF token generation"
echo "   ✓ CSRF token verification"
echo "   ✓ Token validation on requests"
echo ""

echo "9. SESSION SECURITY"
echo "   ✓ Tab visibility monitoring"
echo "   ✓ Session timeout detection"
echo "   ✓ Activity logging"
echo "   ✓ Last activity tracking"
echo ""

echo "10. ATTACK PREVENTION"
echo "    ✓ DDoS protection (multi-level rate limiting)"
echo "    ✓ Dictionary attack prevention"
echo "    ✓ Brute force prevention"
echo "    ✓ Injection attacks prevention"
echo "    ✓ File upload prevention"
echo ""

echo "📊 RATE LIMITING DETAILS:"
echo "========================="
echo "Per Minute: 20 requests"
echo "Per Hour: 200 requests"
echo "Per Day: 2000 requests"
echo "Block Duration: 1 hour (after limit exceeded)"
echo "Window: Sliding window algorithm"
echo ""

echo "🔐 ENVIRONMENT VARIABLES TO SET:"
echo "================================"
echo "In your .env.local or Vercel environment:"
echo ""
echo "OPENROUTER_API_KEY=your_api_key_here"
echo "ALLOWED_ORIGIN=https://your-domain.com"
echo "NODE_ENV=production"
echo ""

echo "🚀 HOW TO CUSTOMIZE SECURITY:"
echo "============================="
echo ""
echo "1. Modify Client-Side Security (public/security.js):"
echo "   - Adjust config object at the top"
echo "   - Modify rate limits"
echo "   - Add/remove protection mechanisms"
echo ""
echo "2. Modify Server-Side Security (api/proxy.js):"
echo "   - Edit RATE_LIMIT_CONFIG"
echo "   - Update allowed models list"
echo "   - Modify spam detection patterns"
echo "   - Add/remove user-agent rules"
echo ""

echo "📈 MONITORING & DEBUGGING:"
echo "=========================="
echo "View security alerts in browser console:"
echo "1. Open browser Developer Tools (after security bypass)"
echo "2. Check 'SECURITY' warning logs"
echo "3. Check sessionStorage for alerts:"
echo "   - sessionStorage.getItem('security_alerts')"
echo ""

echo "📝 LOGGING LOCATIONS:"
echo "===================="
echo "Browser Console:"
echo "  - 🛡️ HeaNg Security System Initialized"
echo "  - ⚠️ Security alerts and warnings"
echo "  - [SECURITY] Messages"
echo ""
echo "Server Logs (Vercel):"
echo "  - ✅ Successful requests"
echo "  - ⏱️ Rate limit events"
echo "  - 🚨 Spam/attack detection"
echo "  - ❌ Errors and failures"
echo ""

echo "🛡️ BEST PRACTICES:"
echo "=================="
echo "1. Always use HTTPS (enforced via CSP)"
echo "2. Keep security.js updated"
echo "3. Monitor rate limit violations"
echo "4. Review suspicious activity regularly"
echo "5. Test security measures in development"
echo "6. Keep API keys secure in environment variables"
echo "7. Update blocked bot patterns regularly"
echo "8. Review CSP policies regularly"
echo ""

echo "⚠️ IMPORTANT NOTES:"
echo "=================="
echo "1. Developer Tools blocking has limitations in production browsers"
echo "2. Determined attackers can bypass client-side protections"
echo "3. Always implement server-side validation (already done)"
echo "4. Rate limiting is per IP in current implementation"
echo "5. For production, consider Redis for distributed rate limiting"
echo ""

echo "✅ Security setup complete!"
echo "Your application is now protected against:"
echo "  • DDoS attacks"
echo "  • Spam and malicious content"
echo "  • Developer tools misuse"
echo "  • SQL injection"
echo "  • XSS attacks"
echo "  • CSRF attacks"
echo "  • Malicious bots"
echo "  • Rate limit abuse"
echo ""
